### ISSUE TITLE
xMission LkMex Whitelist

### ISSUE THREAD

**Issue by xMissionMultiversx** [ElrondNetwork/elrond-specs#32]
## Name of the project

Elrond Moon Mission

## Description of the project

Elrond Moon Mission is a collection of 3018 uniques NFTs on the MultiverseX blockchain.

Website: https://moonmission.io/
dApp; https://apollo.moonmission.io/moon-mission

## Purpose

Elrond Moon Missions is a community investment project. The funds are held in a portfolio and votes are taken on the management of the funds.

Following a community vote, a change of ownership was decided and a new DAO wallet was created.

The funds have been transferred except for the LkMex which are now blocked.

I'm here to make a request so that the LkMex V1 can be transferred between the two wallets and can be used in the xEchange and in our new investment management strategy.

Old wallet : erd1hupwkm6ls5kldvhzd02yhxy995gxtmv7px5l3t5l8jtu28jfqtlq040k9n
New wallet : erd1l6myu3c0xa9tcu8gcexuw59kmrj8rlanlsaywyhclnq3plp22k8s5ptk5n

**Comment by PABourdais** [comment]
You have to open a Pull Request to request the WL.
But they don't allow wallet, so you will loose your time doing it.

**Comment by schimih** [comment]
Hey @xMissionMultiversx ,
please open a PR here: https://github.com/multiversx/mx-specs/pulls.
Thanks :raised_hands:
